# dev branch
[parity]
chain = "spec.json"
base_path = "parity"
[network]
bootnodes=["enode://0e61be1dccfca9050d47b973b8c49420bc8431a1aad56d85d0f95dff487398f0e5c773c4cbb6c2d54238528727d1039f59fcbb77409378dc46ec5fbaee5f1f74@13.90.94.0:30300"]
port = 30300
discovery=true
[rpc]
cors = "all"
interface = "all"
hosts = ["all"]
port = 8540
apis = ["web3", "eth", "net", "personal", "parity", "parity_set", "traces", "rpc", "parity_accounts"]
