# dev-mainnet branch
[parity]
chain = "spec.json"
base_path = "parity"
[network]
max_pending_peers = 16
port = 30300
discovery=true
[rpc]
cors = "all"
interface = "all"
hosts = ["all"]
port = 8545
apis = ["web3", "eth", "net", "parity", "traces", "rpc", "secretstore"]
