# dev branch
[parity]
chain = "spec.json"
base_path = "parity"
[network]
bootnodes=["enode://4a580a2f59bf481cc31ffcb675242c2771e0936988d0e4ca1efee2264326c442ef8d8b05ec9370bafe49c6541b7e3c2ee643ac2428583bcbd813d6a69ba0264b@40.71.41.241:30300"]
port = 30300
discovery=true
[rpc]
cors = "all"
interface = "all"
hosts = ["all"]
port = 8540
apis = ["web3", "eth", "net", "personal", "parity", "parity_set", "traces", "rpc", "parity_accounts"]
