# dev branch
[parity]
chain = "spec.json"
base_path = "parity"
[network]
bootnodes=["enode://a74271cb4b9caf14f5481d289f3aaf65c2f0e1c41c2d810c2491fdbf1ee47f1f6d7a7ebd18430a56bc7e6634cd289ef50a6d35a40f72283cf7299f4b96e77059@13.92.184.236:30300"]
port = 30300
discovery=true
[rpc]
cors = "all"
interface = "all"
hosts = ["all"]
port = 8540
apis = ["web3", "eth", "net", "personal", "parity", "parity_set", "traces", "rpc", "parity_accounts"]
