# dev-mainnet branch
[parity]
chain = "spec.json"
base_path = "parity"
[network]
port = 30303
[rpc]
apis = ["web3", "eth", "parity", "parity_set", "net", "traces", "rpc"]
[account]
password = ["node.pwd"]
[mining]
force_sealing = true
engine_signer = "0xdd0bb0e2a1594240fed0c2f2c17c1e9ab4f87126"
reseal_on_txs = "none"
