# dev-mainnet branch
[parity]
chain = "spec.json"
base_path = "parity"
[network]
port = 30300
discovery=true
max_pending_peers = 16
[rpc]
cors = "all"
interface = "all"
hosts = ["all"]
port = 8545
apis = ["web3", "eth", "net", "personal", "parity", "parity_set", "traces", "rpc", "parity_accounts"]
[ui]
interface = "0.0.0.0"
port = 8180
[websockets]
disable = false
port = 8546
interface = "all"
origins = ["all"]
apis = ["web3", "eth", "net", "parity", "traces", "rpc", "secretstore"]
hosts = ["all"]
[dapps]
cors = "all"
interface = "0.0.0.0"
hosts = ["all"]
port = 8080
[account]
password = ["node.pwd"]
[mining]
force_sealing = true
engine_signer = "0xdd0bb0e2a1594240fed0c2f2c17c1e9ab4f87126"
reseal_on_txs = "none"
